- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDCC-3684
```
[ ] Yes
[X] No
```
> Create DB, S2S secret and DB secrets

- src/main/resources/application.yaml
Added /rd/ to the import statement
```
[ ] Yes
[ x] No
```
> added /rd/ to the import statement [ minor update]

- Jenkinsfile_CNP
- infrastructure/main.tf
NA
Fix TF env issue
```
[ ] Yes
[X] No
```
> Fix env issue

- src/main/resources/db/migration/V1_4__create_view_mv_list_of_values .sql
https://tools.hmcts.net/jira/browse/RDCC-3711
Create a new View for LOV
```
[ ] Yes
[ x] No
```
> Feat:Create a new View for LOV

- Jenkinsfile_CNP
- Jenkinsfile_nightly
> Add nightly schedule configuration

- Jenkinsfile_CNP
- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-3808
- fix: RDCC-3808 added enableDbMigration jenkins stage
- updated the versions 
```
[ ] Yes
[x] No
```
> fix: RDCC-3808 added enableDbMigration jenkins stage and updated the versions

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/RDCC-3808
fix: Added postgres port secret config
```
[ ] Yes
[x] No
```
> fix: Added postgres port secret config

- build.gradle
build.gradle version updates according to bot suggestions
```
[ ] Yes
[ x] No
```
> update build.gradle according to bot changes

- src/main/resources/db/migration/V1_5__insert_additional_facilities.sql
- src/main/resources/db/migration/V1_6__update_view_mv_list_of_values.sql
Create and Insert Additional_Details Table
```
[ ] Yes
[ X] No
```
> Create and Insert Additional_Facilities Table

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/RDCC-3477
Gradle Upgrade to 7.3.3
```
[ ] Yes
[x] No
```
> Commits to support Gradle 7.3.3

- src/main/java/uk/gov/hmcts/reform/cdapi/oidc/JwtGrantedAuthoritiesConverter.java
- src/test/java/uk/gov/hmcts/reform/cdapi/controllers/CrdApiControllerTest.java
- src/test/java/uk/gov/hmcts/reform/cdapi/domain/CaseFlagTest.java
- src/test/java/uk/gov/hmcts/reform/cdapi/domain/FlagDetailTest.java
- src/test/java/uk/gov/hmcts/reform/cdapi/domain/FlagTest.java
- src/test/java/uk/gov/hmcts/reform/cdapi/exception/CommonDataApiExceptionTest.java
- src/test/java/uk/gov/hmcts/reform/cdapi/exception/InvalidRequestExceptionTest.java
- src/test/java/uk/gov/hmcts/reform/cdapi/exception/ResourceNotFoundExceptionTest.java
https://tools.hmcts.net/jira/browse/RDCC-3462
Address remaining Sonar issues in Ref Data repos
```
[ ] Yes
[X] No
```
> fixed sonar issues

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-3947
```
[ ] Yes
[x] No
```
> RDCC-3947: Fixing CVE

- src/functionalTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCaseFlagByServiceIdFunctionalTest.java
- src/main/java/uk/gov/hmcts/reform/cdapi/config/RestAuthenticationEntryPoint.java
- src/main/java/uk/gov/hmcts/reform/cdapi/config/SecurityConfiguration.java
https://tools.hmcts.net/jira/browse/RDCC-3449
https://tools.hmcts.net/jira/browse/RDCC-3449
```
[ ] Yes
[x] No
```
> handled idam bearer token exception

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4088
Fix nightly build failure due to CWE-862: Missing Authorization
```
[ ] Yes
[x] No
```
> RDCC-4088 Fix nightly build failure due to CWE-862: Missing Authorization

- charts/rd-commondata-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-4139
Updated java chart version to 3.7.3
```
[ ] Yes
[x] No
```
> fix: Updated java chart version to 3.7.3

- build.gradle
Jackson data bind CVE Fix 
```
[ ] Yes
[X] No
```
> cve fix for jackson bind

- src/integrationTest/resources/db/testmigration/V1_2__init_table_flag_details.sql
- src/main/resources/db/migration/V1_3__alter_flag_details.sql
https://tools.hmcts.net/jira/browse/RDCC-4149
Altered flag details table to add new mrd date columns
```
[ ] Yes
[x] No
```
> feat: RDCC-4149 Altered flag details table to add new mrd date columns

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/cdapi/CommonDataApiFunctionalTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/cdapi/client/CommonDataApiClient.java
https://tools.hmcts.net/jira/browse/RDCC-4236
Added handle for 404 scenarios in aat
```
[ ] Yes
[x] No
```
> RDCC-4236_fix: Fix master build

- charts/rd-commondata-api/Chart.yaml
- src/main/java/uk/gov/hmcts/reform/cdapi/exception/handler/GlobalExceptionHandler.java
- src/test/java/uk/gov/hmcts/reform/cdapi/exception/handler/GlobalExceptionHandlerTest.java
> Handle Verbose Error Messages

- src/main/java/uk/gov/hmcts/reform/cdapi/repository/ListOfVenueRepository.java
Pointing to new Table Lov the Flag service end point
```
[ ] Yes
[X] No
```
> Point view to LOV Table

- build.gradle
- src/main/java/uk/gov/hmcts/reform/cdapi/service/impl/CrdServiceImpl.java
Fix Functional Test Issues 
```
[ ] Yes
[x] No
```
> Functional Test fix

- .github/workflows/combine-prs.yml
NA
Add combine PR github action
```
[ ] Yes
[X] No
```
> Add combine PR github action

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4504
fix for cve 2022-22968
```
[ ] Yes
[X] No
```
> commondata -Nightly build failure -25/04/2022 

- build.gradle
Nightly Fix: Increasing Mutation Versions
```
[ ] Yes
[x] No
```
> Nightly Fix: Increasing Mutation Versions

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4633
```
[ ] Yes
[X] No
```
> fix for CVE 2022-25647

- build.gradle
JIRA link
https://tools.hmcts.net/jira/browse/RDCC-4614
Change description
RD API app-insight is not generating logs for api.
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[ x] No
> Feat:Changes made to fix app-insights issue

- src/main/java/uk/gov/hmcts/reform/cdapi/config/SecurityConfiguration.java
- src/main/java/uk/gov/hmcts/reform/cdapi/config/SecurityEndpointFilter.java
- src/main/java/uk/gov/hmcts/reform/cdapi/exception/UnauthorizedException.java
- src/main/java/uk/gov/hmcts/reform/cdapi/repository/IdamRepository.java
- src/test/java/uk/gov/hmcts/reform/cdapi/exception/UnauthorizedExceptionTest.java
- src/test/java/uk/gov/hmcts/reform/cdapi/repository/IdamRepositoryTest.java
https://tools.hmcts.net/jira/browse/RDCC-4680
To handle 500 HTTP responses
```
[ ] Yes
[ x] No
```
> Feat:To handle 500 HTTP responses

- renovate.json
*### JIRA link  ###
https://tools.hmcts.net/jira/browse/RDCC-4822
Configured renovate
```
[ ] Yes
[x] No
```
> config: RDCC-4822 Configured renovate

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4849
Collating DependaBot PRs
```
[ ] Yes
[x] No
```
> RDCC-4849: Collating DependaBot PRs

- src/main/resources/db/migration/V1_8__Insert_table_flag_details.sql
JIRA link (if applicable)
RDCC-4906
Change description
CRD : Test Flag Details
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[ X] No
> RDCC-4906 CRD : Test Flag Details Changes

- charts/rd-commondata-api/Chart.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-5007
Adding Suppression for `CVE-2022-34305`
```
[ ] Yes
[x] No
```
> RDCC-5007: Adding Suppression for `CVE-2022-34305`

- charts/rd-commondata-api/Chart.yaml
- charts/rd-commondata-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/RDCC-5039
Upgrade java chart 
```
[ ] Yes
[x] No
```
> config: RDCC-5041 Upgrade java chart

- charts/rd-commondata-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-5145
Upgrade java chart version
```
[ ] Yes
[x] No
```
> RDCC-5145 Upgrade java chart version

- config/fortify-client.properties
https://tools.hmcts.net/jira/browse/RDCC-4997
Changes made to add and fix checkstyle and fortifyscan
```
[ ] Yes
[ x] No
```
> Feat:RDCC-4997:Changes made to add and fix checkstyle

- config/owasp/suppressions.xml
> adding suppression for CVE-2022-25857

- src/integrationTest/resources/db/testmigration/V1_8__Insert_table_flag_details.sql
- src/integrationTest/resources/db/testmigration/V1_9__Insert_table_flag_details.sql
- src/main/resources/db/migration/V1_9__Insert_table_flag_details.sql
Insert values in to flag details table
```
[ ] Yes
[X] No
```
> Insert value in to Flag Details Table

- build.gradle
- config/owasp/suppressions.xml
CVE issue
```
[ ] Yes
[X] No
```
> CVE Issues

- src/contractTest/java/uk/gov/hmcts/reform/cdapi/provider/CommonDataApiProviderTest.java
- src/functionalTest/java/uk/gov/hmcts/reform/cdapi/CommonDataApiFunctionalTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCategoriesIntegrationTest.java
- src/main/java/uk/gov/hmcts/reform/cdapi/domain/CategoryKey.java
- src/main/java/uk/gov/hmcts/reform/cdapi/domain/ListOfValueDto.java
- src/main/java/uk/gov/hmcts/reform/cdapi/domain/QuerySpecification.java
- src/main/java/uk/gov/hmcts/reform/cdapi/service/impl/CrdServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/cdapi/helper/CrdTestSupport.java
- src/test/java/uk/gov/hmcts/reform/cdapi/service/impl/CrdServiceImplTest.java
ServiceID Changes
```
[ ] Yes
[X] No
```
> service id changes

- src/main/java/uk/gov/hmcts/reform/cdapi/controllers/response/Category.java
- src/test/java/uk/gov/hmcts/reform/cdapi/exception/UnauthorizedExceptionTest.java
https://tools.hmcts.net/jira/browse/RDCC-5596
```
[ ] Yes
[X] No
```
> Code Smell Changes : RDCC-5596

- build.gradle
- src/integrationTest/resources/db/testmigration/V1_10__update_table_flag_details.sql
- src/main/resources/db/migration/V1_10__update_table_flag_details.sql
https://tools.hmcts.net/jira/browse/RDCC-5741
Case Flags : Refresh Flag Details in all lower environments
```
[ ] Yes
[X] No
```
> updated flag details

- src/integrationTest/resources/db/testmigration/V1_10__update_table_flag_details.sql
- src/main/resources/db/migration/V1_10__update_table_flag_details.sql
Reverts hmcts/rd-commondata-api#226
> Revert "updated flag details"

- src/integrationTest/resources/db/testmigration/V1_11__alter_flag_service_details.sql
- src/main/resources/db/migration/V1_11__alter_flag_service_details.sql
https://tools.hmcts.net/jira/browse/RDCC-5571
```
[ ] Yes
[X] No
```
> Case Flags : Add two new columns in Flag Service table : Rdcc 5571 

- Jenkinsfile_nightly
- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-5853
enabling Fortify Scan
```
[ ] Yes
[x] No
```
> RDCC-5853: enabling Fortify Scan

- src/integrationTest/resources/db/testmigration/V1_11__alter_flag_service_details.sql
- src/main/resources/db/migration/V1_11__alter_flag_service_details.sql
Reverts hmcts/rd-commondata-api#232
> Revert "Case Flags : Add two new columns in Flag Service table : Rdcc 5571 "

- build.gradle
https://tools.hmcts.net/jira/browse/RDCC-5853
Fix - Syncing Fortify Config with PRD
```
[ ] Yes
[x] No
```
> RDCC-5853: Fix - Syncing Fortify Config with PRD

- src/integrationTest/resources/db/testmigration/V1_10__update_table_flag_details.sql
- src/main/resources/db/migration/V1_10__update_table_flag_details.sql
https://tools.hmcts.net/jira/browse/RDCC-5741
Case Flags : Refresh Flag Details in all lower environments
```
[ ] Yes
[ X] No
```
> RDCC-5741:updated flag details

- src/integrationTest/resources/db/testmigration/V1_10__update_table_flag_details.sql
- src/main/resources/db/migration/V1_10__update_table_flag_details.sql
Reverts hmcts/rd-commondata-api#231
> Revert "RDCC-5741:updated flag details"

- src/integrationTest/resources/db/testmigration/V1_11__alter_flag_service_details.sql
- src/main/resources/db/migration/V1_11__alter_flag_service_details.sql
Reverts hmcts/rd-commondata-api#239
> Revert "Revert "Case Flags : Add two new columns in Flag Service table : Rdcc 5571 ""

- src/integrationTest/resources/db/testmigration/V1_13__Insert_table_flag_details.sql
- src/main/resources/db/migration/V1_13__Insert_table_flag_details.sql
https://tools.hmcts.net/jira/browse/RDCC-5914
Case Flags : Refresh Flag Details with new file
```
[ ] Yes
[X] No
```
> RDCC-5914-flag details inserts

- src/main/java/uk/gov/hmcts/reform/cdapi/service/impl/CaseFlagServiceImpl.java
sonarissues
```
[ ] Yes
[ x] No
```
> sonar fixes

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-6259
```
[ ] Yes
[X] No
```
> cve issue fix

- build.gradle
- config/owasp/suppressions.xml
- src/test/java/uk/gov/hmcts/reform/cdapi/service/impl/CaseFlagServiceImplTest.java
https://tools.hmcts.net/jira/browse/RDCC-6259
Adding & Upgrading Dependencies to fix `dependency-check` issue and `CVEs` that are caused as a result
```
[ ] Yes
[x] No
```
> RDCC-6259: Adding & Upgrading Dependencies

- charts/rd-commondata-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-1707
Upgraded helm chart version to `4.0.11`
```
[ ] Yes
[x] No
```
> RDCC-1707: Upgrade helm chart version to latest

- audit.json
https://tools.hmcts.net/jira/browse/RDCC-6364
Adding entry to `audit.json` to fix Security Scan stage in Nightly Build
```
[ ] Yes
[x] No
```
> RDCC-6364: Adding entry to `audit.json`

- charts/rd-commondata-api/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-6374
Upgrading chart version to `4.0.13`
```
[ ] Yes
[x] No
```
> RDCC-6374: Upgrading chart version to 4.0.13

- .github/renovate.json
https://tools.hmcts.net/jira/browse/RDCC-6421
RDCC-6421-renovate.json update
```
[ ] Yes
[x] No
```
> RDCC-6421-renovate.json update

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-6428
Address CVEs in all Reference Data repositories - Common Reference Data
```
[ ] Yes
[x ] No
```
> Feat:Address CVEs in all Reference Data repositories - Common Reference Data

- src/main/java/uk/gov/hmcts/reform/cdapi/controllers/CaseFlagApiController.java
- src/main/java/uk/gov/hmcts/reform/cdapi/controllers/CrdApiController.java
- src/main/java/uk/gov/hmcts/reform/cdapi/controllers/RootController.java
- src/main/java/uk/gov/hmcts/reform/cdapi/oidc/JwtGrantedAuthoritiesConverter.java
- src/main/java/uk/gov/hmcts/reform/cdapi/service/impl/CaseFlagServiceImpl.java
https://tools.hmcts.net/jira/browse/RDCC-6528
Address Sonar Coverage issues
```
[ ] Yes
[x] No
```
> RDCC-6528-Address Sonar Coverage issues

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-6682
address failing night build.
appropriate fix to follow in [DTSRD-47](https://tools.hmcts.net/jira/browse/DTSRD-47)
```
[ ] Yes
[x] No
```
> RDCC-6682: suppress CVE-2023-20861

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSRD-155
Changed spring framework version to 5.3.26 to fix CVE-2023-20860
```
[ ] Yes
[x] No
```
> Upped spring framework version to fix CVE-2023-20860

- audit.json
https://tools.hmcts.net/jira/browse/DTSRD-166
Add missed changes to audit.json to fix nightlys
```
[ ] Yes
[x] No
```
> Add missed changes to audit.json to fix nightlys

- src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCategoriesIntegrationTest.java
https://tools.hmcts.net/jira/browse/RDCC-5918
```
[ ] Yes
[X] No
```
> Enhance rd-commondata-api integration test cases

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/cdapi/service/impl/CaseFlagServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/cdapi/service/impl/CaseFlagServiceImplTest.java
update "other" flag details as in case flags V2
```
[ ] Yes
[X] No
```
> Updating Case Flag Details

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSRD-47
Removed suppression for remedied CVE
```
[ ] Yes
[x] No
```
> removed suppression

- build.gradle
https://tools.hmcts.net/jira/browse/DTSRD-550
Fix CVE-2023-20883
```
[ ] Yes
[x] No
```
> DTSRD-552: Fix CVE-2023-20883

- build.gradle
- config/owasp/suppressions.xml
> CVE suppression   CVE-2023-34034

- .github/renovate.json
- renovate.json
- Updating renovate config.
https://tools.hmcts.net/jira/browse/DTSRD-1227
```
[ ] Yes
[x] No
```
> DTSRD-1227

- infrastructure/main.tf
> Dtsrd 1176

- infrastructure/main.tf
- infrastructure/variables.tf
> DTSRD-1176

- infrastructure/main.tf
- infrastructure/variables.tf
DTSRD-1234
```
[ ] Yes
[ *] No
```
> DTSRD-1234.Upgrade Postgresss to V15

- infrastructure/variables.tf
> DTSRD-1234

- infrastructure/variables.tf
> Dtsrd-1234 

- infrastructure/variables.tf
> DTSRD-1213.reverting the changes done for upgrade to postgresV15

- infrastructure/main.tf
DTSRD-1234
```
[ ] Yes
[ ] No
```
> DTSRD-1234 Upgrade to V15

- infrastructure/main.tf
- infrastructure/variables.tf
> DTSRD-1234.Changing Database name for V15

- Jenkinsfile_CNP
DTSRD-1446
```
[ ] Yes
[ ] No
```
> DTSRD-1466.Remove branches to sync -commondata demo and master

- Jenkinsfile_CNP
- build.gradle
- charts/rd-commondata-api/Chart.yaml
DTSRD-1466
```
[ ] Yes
[ *] No
```
> DTSRD-1466.DTSRD-1466.merging changes to stop sync and adding cve fix for ithc and perftest

- infrastructure/main.tf
- infrastructure/provider.tf
- infrastructure/variables.tf
DTSRD-1234
```
[ ] Yes
[ ] No
```
> DTSRD-1234-2.merging V15 changes to perftest branch

- README.md
- config/owasp/suppressions.xml
- Minor update to README.md to enable new PR.
https://tools.hmcts.net/jira/browse/DTSRD-1473
```
[ ] Yes
[x] No
```
> DTSRD-1473

- src/main/resources/application.yaml
> change connection pool size

- infrastructure/main.tf
- infrastructure/provider.tf
- infrastructure/variables.tf
> Upgrading ithc branch to V16 and adding subnet_suffix

- Jenkinsfile_CNP
- infrastructure/main.tf
- infrastructure/provider.tf
- infrastructure/variables.tf
> DTSRD-1893.Upgrading main branch to V16 and adding subnet_suffix 

- infrastructure/main.tf
- infrastructure/variables.tf
> Dtsrd 1234-3.Adding force_user_permissions_trigger to get DTS CFT DB Access Reader access

- infrastructure/main.tf
- infrastructure/variables.tf
… access
```
[ ] Yes
[ ] No
```
> DTSRD-2065 .Adding force_user_permissions_trigger to get access to DTS JIT Access rd DB Reader SC user

- src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCategoriesIntegrationTest.java
- src/main/java/uk/gov/hmcts/reform/cdapi/service/impl/CrdServiceImpl.java
https://tools.hmcts.net/jira/browse/DTSRD-2109
Introduces sorting by lov_order
```
[ ] Yes
[x] No
```
> Reordering of hearing attendance in HMC (List of Values)

- src/main/java/uk/gov/hmcts/reform/cdapi/service/impl/CrdServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/cdapi/helper/CrdTestSupport.java
- src/test/java/uk/gov/hmcts/reform/cdapi/service/impl/CrdServiceImplTest.java
https://tools.hmcts.net/jira/browse/DTSRD-2109
Sorting by lov_order if defined and else sort by valueEn
```
[ ] Yes
[x] No
```
> Dtsrd 2109 2

- infrastructure/main.tf
- infrastructure/prod.tfvars
- infrastructure/variables.tf
> DTSRD-2065-3.Schema Owner Fix

- src/integrationTest/java/uk/gov/hmcts/reform/cdapi/RetrieveCategoriesIntegrationTest.java
- src/integrationTest/resources/db/testmigration/V1_6__Alter_List_Of_Values.sql
- src/main/java/uk/gov/hmcts/reform/cdapi/domain/QuerySpecification.java
> DTSRD-2215.Fixing query to fetch listof values category by service id

- build.gradle
- config/owasp/suppressions.xml
…nged req
```
[ ] Yes
[ ] No
```
> cve fix for 2023-1370

- charts/rd-commondata-api/Chart.yaml
- charts/rd-commondata-api/values.yaml
> DTSRD-2442: PI33 Configure spot instances in non-production

- infrastructure/aat.tfvars
- infrastructure/main.tf
- infrastructure/variables.tf
> Fixing azure extensions

- infrastructure/main.tf
> Update schema ownership and force permission

- charts/rd-commondata-api/Chart.yaml
- charts/rd-commondata-api/values.yaml
- infrastructure/main.tf
- infrastructure/provider.tf
> DTSRD-2750.Decomissioning single server

- infrastructure/main.tf
> Dtsrd 2750

- build.gradle
- config/checkstyle/checkstyle.xml
- config/owasp/suppressions.xml
- gradle/wrapper/gradle-wrapper.properties
- src/contractTest/java/uk/gov/hmcts/reform/cdapi/provider/CommonDataApiProviderTest.java
https://tools.hmcts.net/jira/browse/DTSRD-2766
- update gradle and plugins
- checkstyle
- suppressions cleanup
```
[ ] Yes
[x] No
```
> DTSRD-2766

- infrastructure/provider.tf
https://tools.hmcts.net/jira/browse/DTSRD-2895
Update azurerm to 3.106
```
[ ] Yes
[x] No
```
> DTSRD-2895

- src/functionalTest/java/uk/gov/hmcts/reform/cdapi/CommonDataApiFunctionalTest.java
> Fix Build -data changed-fix- Update CommonDataApiFunctionalTest.java

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> fixing build

- build.gradle
> Fix build mutation

- build.gradle
> Trigger master pipeline

- .github/workflows/swagger.yml
- src/integrationTest/java/uk/gov/hmcts/reform/cdapi/config/SwaggerPublisherTest.java
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/DTSRD-3562
Swagger Publishing
```
[ ] Yes
[x] No
```
> DTSRD-3562 Swagger Publishing

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/DTSRD-3619
- remedy for CVE-2024-22233
- gradle 8.10.2
```
[ ] Yes
[x] No
```
> DTSRD-3619

- src/test/java/uk/gov/hmcts/reform/cdapi/helper/CrdTestSupport.java
- src/test/java/uk/gov/hmcts/reform/cdapi/service/impl/CrdServiceImplTest.java
> Fixing mutation tests

- src/test/java/uk/gov/hmcts/reform/cdapi/helper/CrdTestSupport.java
- src/test/java/uk/gov/hmcts/reform/cdapi/service/impl/CrdServiceImplTest.java
> Fix master build

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CME-248
```
[ ] Yes
[ x] No
```
> CME-248: Disable sync to ITHC for database monitoring testing

- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CME-248
```
[ ] Yes
[x ] No
```
> CME-248: Database monitoring and alerting on RD repositories

- infrastructure/provider.tf
https://tools.hmcts.net/jira/browse/CME-301
```
[ ] Yes
[ x] No
```
> CME-301: Update azurerm

- build.gradle
Update HMCTS gradle plugin to 0.12.64
```
[ ] Yes
[x] No
```
> Update HMCTS gradle plugin to 0.12.64

- charts/rd-commondata-api/Chart.yaml
> CME-412: Refdata Helm OCI Update rd-commondata-api

- .github/renovate.json
> Align renovate config with RD components
